# Generated by Django 2.1.8 on 2020-09-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_student',
            name='batch',
            field=models.IntegerField(),
        ),
    ]
