# Generated by Django 2.2.4 on 2020-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='googlePlus_profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='instagram_profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter_profile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='uni',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='uni_sub',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
