# Generated by Django 2.1.8 on 2020-09-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200909_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_photo',
            new_name='photo',
        ),
    ]
