# Generated by Django 2.2.4 on 2020-10-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200909_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_information',
            name='institution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact_information',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
