# Generated by Django 2.2.4 on 2020-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201022_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_information',
            name='institution',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='phone',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
