# Generated by Django 2.2.4 on 2020-10-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0002_auto_20190519_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='youtube_vide_link',
        ),
    ]
